### ISSUE TITLE
[Feature request] Could you add a toggle for disabling shadows on a selected prop also?

### ISSUE THREAD

**Issue by WolfeStrider** [IcedCoffeee/disablelighting#1]
Would be very useful in builds

**Comment by IcedCoffeee** [comment]
i was taking a break from gmod when this was posted, but i've updated it to include this in https://github.com/IcedCoffeee/disablelighting/commit/5674695f23d5047633180223876948fac591af20, and pushed it to the workshop. let me know how it goes... if you still play gmod lol

**Comment by WolfeStrider** [comment]
Yes it helped a lot, thank you for updating the mod although there was a bug created seen in #2
